<?php

/**
 * @file
 * Contains commonmark.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commonmark_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commonmark module.
    case 'help.page.commonmark':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Converts Markdown to HTML based on the CommonMark spec via thephpleague/commonmark PHP library, created and maintained by The League of Extraordinary Packages.') . '</p>';
      return $output;

    default:
  }
}
